blank_issues_enabled: false
contact_links:
  - name: 💡 Feature Request
    url: https://github.com/iptv-org/iptv/discussions/new
    about: For any ideas or feature requests
  - name: ❓ Ask a Question
    url: https://github.com/iptv-org/iptv/discussions/new
    about: Ask questions about this project
