blank_issues_enabled: false
contact_links:
  - name: Vditor 官方讨论区
    url: https://ld246.com/tag/vditor
    about: 欢迎到这里反馈问题和提出建议，国内访问的话会比 GitHub 更丝滑流畅一些
  - name: 思源笔记问题反馈
    url: https://github.com/siyuan-note/siyuan
    about: 思源笔记相关问题请到这里反馈